### ISSUE TITLE
[GET] Channels - Documentation Discrepancy

### ISSUE THREAD

**Issue by TheAlienKnight** [revoltchat/documentation#22]
While working on a project using the API, I noticed the documentation isn't returning what is expected/currently documented for the `/channels/:id` section

[Direct Documentation Link](https://developers.revolt.chat/api/#tag/Channel-Information/paths/~1channels~1:channel/get)

Expected / Currently Documented
![Screenshot](https://cloud.ajnicoloff.me/s/4E3JdaoZqaNrBz4/preview)

Returned (Example)
![Screenshot](https://cloud.ajnicoloff.me/s/SHXkcCCeyYJdcCm/preview)

For clarification, I made sure the missing content was available by setting a server icon, and description before posting this 👍

**Comment by insertish** [comment]
Refer to the schema in the main part of the page, many fields are optional and will not be present in the object.
The right side of the page is simply an example of what could be there.
