### ISSUE TITLE
About revolt

### ISSUE THREAD

**Issue by itsnotsaved** [revoltchat/documentation#8]
**Description**

How to pronounce "revolt"?
Just write the name in latin characters (as wikipedia display the pronunciation) or attach a sound file. Furthermore you can add this to documentation.

**Comment by Albonycal** [comment]
`/rɪˈvoʊlt/`

https://user-images.githubusercontent.com/67057319/133423007-2a083037-7938-4b0f-a84c-d7c07f575616.mp4

**Comment by itsnotsaved** [comment]
@Albonycal thank you :1st_place_medal:
